### ISSUE TITLE
Archive should... archive.

### ISSUE THREAD

**Issue by Eriner** [Eriner/prezto#8]
The `archive` module should be able to archive, not just unarchive and list files. I will create a function that will follow the syntax:

`archive new-achive.7z /path/to/folder/or/file/to/be/achived`

this will create an archive of the specified type in the current directory.

**Comment by Brottweiler** [comment]
:+1: Will help so you don't have to remember all those options. Maybe instead of `archive <type>`, make it so that it detects it when you specify the filename, like `archive package.7z /path/to/folder/or/file`?

**Comment by Eriner** [comment]
You're right. That is a better solution.

**Comment by Eriner** [comment]
Archive function added in https://github.com/Eriner/prezto/commit/5a2f48980cd80e513d097d9af7f5de50f93961e0

I have tested all sane scenarios, and everything works as expected.
